<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>uiApiAutomation</groupId>
	<artifactId>uiApiAutomation</artifactId>
	<version>0.0.1-SNAPSHOT</version>

	<name>uiApiAutomation</name>
	<!-- FIXME change it to the project's website -->
	<url>http://www.example.com</url>

	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<maven.compiler.release>24</maven.compiler.release>
		<maven.cucumber.version>7.33.0</maven.cucumber.version>
		<maven.junit.version>6.1.0-M1</maven.junit.version>
		<maven.cucumber.jvm.deps>1.0.6</maven.cucumber.jvm.deps>
		<maven.gherkin.jvm.deps>1.0.6</maven.gherkin.jvm.deps>
		<maven.lombok.version>1.18.42</maven.lombok.version>
		<maven.selenium.version>4.39.0</maven.selenium.version>
		<maven.webdrivermanager.version>6.3.3</maven.webdrivermanager.version>
		<maven.spring.boot.version>4.0.1</maven.spring.boot.version>
		<maven.restAssured.version>6.0.0</maven.restAssured.version>
		<maven.validationApi.version>4.0.0-M1</maven.validationApi.version>
		<maven.surefire.plugin.version>3.5.4</maven.surefire.plugin.version>
		<maven.compiler.plugin.version>3.14.1</maven.compiler.plugin.version>
		<maven.clean.plugin.version>3.5.0</maven.clean.plugin.version>
		<jackson.dataformat.yaml.version>2.20.1</jackson.dataformat.yaml.version>
		<allure.bom.version>2.32.0</allure.bom.version>
		<maven.extent.report.version>5.1.2</maven.extent.report.version>
		<maven.extent.reports.cucumber.adapter.version>1.14.0</maven.extent.reports.cucumber.adapter.version>
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>io.cucumber</groupId>
				<artifactId>cucumber-bom</artifactId>
				<version>${maven.cucumber.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<dependency>
				<groupId>org.junit</groupId>
				<artifactId>junit-bom</artifactId>
				<version>${maven.junit.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>

			<dependency>
				<groupId>io.qameta.allure</groupId>
				<artifactId>allure-bom</artifactId>
				<version>${allure.bom.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<!-- Cucumber Dependencies -->
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-java</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-core</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-jvm</artifactId>
			<version>${maven.cucumber.version}</version>
			<type>pom</type>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-picocontainer</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-jvm-deps</artifactId>
			<version>${maven.cucumber.jvm.deps}</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-gherkin</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>gherkin-jvm-deps</artifactId>
			<version>${maven.gherkin.jvm.deps}</version>
			<scope>compile</scope>
		</dependency>
		<!-- End of Cucumber Dependencies -->

		<!-- RestAssured Version -->
		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<version>${maven.restAssured.version}</version>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.validation</groupId>
			<artifactId>jakarta.validation-api</artifactId>
			<version>${maven.validationApi.version}</version>
		</dependency>
		<!-- End of RestAssured -->

		<!-- Lombok Dependency -->
		<dependency>
			<groupId>org.projectlombok</groupId>
			<artifactId>lombok</artifactId>
			<version>${maven.lombok.version}</version>
			<scope>compile</scope>
		</dependency>
		<!-- End of Lombok -->

		<!-- Selenium Dependency -->
		<dependency>
			<groupId>org.seleniumhq.selenium</groupId>
			<artifactId>selenium-java</artifactId>
			<version>${maven.selenium.version}</version>
			<scope>compile</scope>
		</dependency>

		<dependency>
			<groupId>io.github.bonigarcia</groupId>
			<artifactId>webdrivermanager</artifactId>
			<version>${maven.webdrivermanager.version}</version>
			<scope>compile</scope>
		</dependency>
		<!-- End of Selenium Dependency -->

		<!-- Spring Dependency -->
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot</artifactId>
			<version>${maven.spring.boot.version}</version>
			<scope>compile</scope>
		</dependency>
		<!-- End of Spring Dependency -->

		<!-- Jackson Dependency -->
		<dependency>
			<groupId>com.fasterxml.jackson.dataformat</groupId>
			<artifactId>jackson-dataformat-yaml</artifactId>
			<version>${jackson.dataformat.yaml.version}</version>
			<scope>compile</scope>
		</dependency>
		<!-- End of Jackson Dependency -->
		<!-- Junit Dependencies -->
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.cucumber</groupId>
			<artifactId>cucumber-junit-platform-engine</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<scope>test</scope>
		</dependency>
		<!--<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-api</artifactId>
			<scope>test</scope>
		</dependency>-->
		<!--<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-suite</artifactId>
			<scope>test</scope>
		</dependency>-->
		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-suite-api</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-suite-engine</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter-engine</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>org.junit.platform</groupId>
			<artifactId>junit-platform-engine</artifactId>
			<scope>test</scope>
		</dependency>
		<!-- End of Junit-->
		<!-- Allure Report Dependency-->
		<dependency>
			<groupId>io.qameta.allure</groupId>
			<artifactId>allure-cucumber7-jvm</artifactId>
			<scope>test</scope>
		</dependency>
		<dependency>
			<groupId>io.qameta.allure</groupId>
			<artifactId>allure-junit-platform</artifactId>
			<scope>test</scope>
		</dependency>
		<!-- End of Allure Report-->
		<!-- Extent Report Dependency -->
		<dependency>
			<groupId>com.aventstack</groupId>
			<artifactId>extentreports</artifactId>
			<version>${maven.extent.report.version}</version>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>tech.grasshopper</groupId>
			<artifactId>extentreports-cucumber7-adapter</artifactId>
			<version>${maven.extent.reports.cucumber.adapter.version}</version>
			<scope>compile</scope>
		</dependency>
		<!-- End of Extent Report-->
	</dependencies>


	<build>
		<pluginManagement><!-- lock down plugins versions to avoid using Maven
			defaults (may be moved to parent pom) -->
			<plugins>
				<!-- clean lifecycle, see
				https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
				<plugin>
					<artifactId>maven-clean-plugin</artifactId>
					<version>${maven.clean.plugin.version}</version>
					<configuration>
						<filesets>
							<fileset>
								<directory>${project.basedir}/test-output</directory>
							</fileset>
						</filesets>
					</configuration>
				</plugin>
				<!-- default lifecycle, jar packaging: see
				https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
				<plugin>
					<artifactId>maven-resources-plugin</artifactId>
					<version>3.3.1</version>
				</plugin>
				<plugin>
					<artifactId>maven-compiler-plugin</artifactId>
					<version>${maven.compiler.plugin.version}</version>
					<configuration>
						<annotationProcessorPaths>
							<path>
								<groupId>org.projectlombok</groupId>
								<artifactId>lombok</artifactId>
								<version>${maven.lombok.version}</version>
							</path>
						</annotationProcessorPaths>
					</configuration>
				</plugin>
				<plugin>
					<artifactId>maven-surefire-plugin</artifactId>
					<version>${maven.surefire.plugin.version}</version>
					<configuration>
						<rerunFailingTestsCount>1</rerunFailingTestsCount>
						<testFailureIgnore>false</testFailureIgnore>
						<test>**/*JunitRunner.java</test>
						<!--<includes>
							<include>**/JunitRunner.java</include>
						</includes>-->
					</configuration>
				</plugin>
				<plugin>
					<artifactId>maven-jar-plugin</artifactId>
					<version>3.4.2</version>
				</plugin>
				<plugin>
					<artifactId>maven-install-plugin</artifactId>
					<version>3.1.2</version>
				</plugin>
				<plugin>
					<artifactId>maven-deploy-plugin</artifactId>
					<version>3.1.2</version>
				</plugin>
				<!-- site lifecycle, see
				https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
				<plugin>
					<artifactId>maven-site-plugin</artifactId>
					<version>3.12.1</version>
				</plugin>
				<plugin>
					<artifactId>maven-project-info-reports-plugin</artifactId>
					<version>3.6.1</version>
				</plugin>
			</plugins>
		</pluginManagement>
	</build>
</project>
